package com.jshubham.ftpservice.cliclient;

import client.FTPServiceClient;
import com.google.protobuf.ByteString;
import com.jshubham.ftpservice.autogenerated.FileAttributesResult;
import com.jshubham.ftpservice.autogenerated.ReadFileResult;
import com.jshubham.ftpservice.autogenerated.Result;
import io.grpc.StatusRuntimeException;
import io.grpc.stub.StreamObserver;
import org.apache.commons.cli.*;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.jspecify.annotations.NonNull;

import java.io.BufferedOutputStream;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.concurrent.CountDownLatch;
import java.util.concurrent.TimeUnit;

public class SampleCLIClient {
    private static final Logger logger = LogManager.getLogger(SampleCLIClient.class);
    private static final String ADD = "add";
    private static final String OUT = "out";
    private static final String DEL = "del";
    private static final String READ = "read";
    private static final String ATTR = "attr";
    private static final String BLOCKING = "blocking";
    private static final String SERVER = "server";

    private void addFile(String server, String fileToAdd, String destFilename) {
        try {
            CountDownLatch countDownLatch = new CountDownLatch(1);
            FTPServiceClient ftpServiceClient;
            FTPServiceClient.FTPServiceClientBuilder builder = new FTPServiceClient.FTPServiceClientBuilder();
            ftpServiceClient = builder.setServerAddress(server).build();

            StreamObserver<Result> responseObserver = new StreamObserver<Result>() {
                @Override
                public void onNext(Result resultResponse) {
                    logger.info("Received result from server: {}", resultResponse.getStatus());
                    countDownLatch.countDown();
                }

                @Override
                public void onError(Throwable t) {
                    logger.error("Error from the server: {} \n {}" , t.toString(), t.getMessage());
                    countDownLatch.countDown();
                }

                @Override
                public void onCompleted() {
                    logger.info("Completed the add file call");
                    countDownLatch.countDown();
                }
            };

            ftpServiceClient.addFile(fileToAdd, destFilename, responseObserver);

            countDownLatch.await(5, TimeUnit.MINUTES);
        } catch (IOException | InterruptedException e) {
            logger.info("Encountered exception {}", e.toString());
        }
    }

    private void deletedFile(String server, String fileToDelete) {
        try {
            CountDownLatch countDownLatch = new CountDownLatch(1);
            FTPServiceClient ftpServiceClient;
            FTPServiceClient.FTPServiceClientBuilder builder = new FTPServiceClient.FTPServiceClientBuilder();
            ftpServiceClient = builder.setServerAddress(server).build();

            StreamObserver<Result> responseObserver = new StreamObserver<Result>() {
                @Override
                public void onNext(Result value) {
                    logger.info("Received delete file result from the server: {}", value.getStatus().toString());
                    countDownLatch.countDown();
                }

                @Override
                public void onError(Throwable t) {
                    logger.error("Error from server: {} \n {}", t.toString(), t.getMessage());
                }

                @Override
                public void onCompleted() {
                    logger.info("Completed delete file call");
                }
            };

            ftpServiceClient.deleteFile(fileToDelete, responseObserver);

            // synchronizing this thread to wait for the async delete file rpc to complete
            countDownLatch.await(5, TimeUnit.MINUTES);
        } catch (IOException | InterruptedException e) {
            logger.info("Encountered exception " + e);
        }
    }

    private void readFile(String server, String fileName) {
        try {
            CountDownLatch countDownLatch = new CountDownLatch(1);
            FTPServiceClient ftpServiceClient;
            FTPServiceClient.FTPServiceClientBuilder builder = (new FTPServiceClient.FTPServiceClientBuilder());

            ftpServiceClient = builder.setServerAddress(server).build();

            logger.info("Initiating read call with the server");

            Path inputPath = Paths.get(fileName);
            Path parentPath = inputPath.getParent();
            String downloadedName = getDownloadedName(inputPath);

            Path targetPath;
            if (Files.isDirectory(Paths.get("ftp-service-client-cli"))) {
                targetPath = Paths.get("ftp-service-client-cli", parentPath != null ? parentPath.resolve(downloadedName).toString() : downloadedName);
            } else {
                targetPath = parentPath != null ? parentPath.resolve(downloadedName) : Paths.get(downloadedName);
            }

            StreamObserver<ReadFileResult> responseObserver = new StreamObserver<ReadFileResult>() {
                private BufferedOutputStream out = null;
                private boolean hasError = false;

                @Override
                public void onNext(ReadFileResult response) {
                    if (response.hasMessage()) {
                        logger.error("Received error result from the server: {}", response.getMessage());
                        hasError = true;
                    } else if (response.hasFileChuck()) {
                        try {
                            if (out == null) {
                                out = new BufferedOutputStream(Files.newOutputStream(targetPath));
                            }
                            ByteString content = response.getFileChuck().getContent();
                            out.write(content.toByteArray());
                        } catch (IOException e) {
                            logger.error("Error writing chunk to file", e);
                            hasError = true;
                        }
                    }
                }

                @Override
                public void onError(Throwable t) {
                    logger.error("Error from the server during download: {}", t.getMessage());
                    closeOutputStreamQuietly();
                    try {
                        Files.deleteIfExists(targetPath);
                    } catch (IOException e) {
                        logger.error("Failed to clean up incomplete file: {}", targetPath, e);
                    }
                    countDownLatch.countDown();
                }

                @Override
                public void onCompleted() {
                    closeOutputStreamQuietly();
                    if (hasError) {
                        logger.error("File download completed but errors occurred. Cleaning up.");
                        try {
                            Files.deleteIfExists(targetPath);
                        } catch (IOException e) {
                            logger.error("Failed to clean up failed file: {}", targetPath, e);
                        }
                    } else {
                        logger.info("File downloaded successfully and saved as: {}", targetPath.toAbsolutePath());
                    }
                    countDownLatch.countDown();
                }

                private void closeOutputStreamQuietly() {
                    try {
                        if (out != null) {
                            out.close();
                        }
                    } catch (IOException e) {
                        logger.error("Failed to close output stream", e);
                    }
                }
            };

            ftpServiceClient.readFile(fileName, responseObserver);

            // Await completion of the stream
            countDownLatch.await(5, TimeUnit.MINUTES);

        } catch (IOException | InterruptedException e) {
            throw new RuntimeException(e);
        }
    }

    private @NonNull String getDownloadedName(Path inputPath) {
        Path fileSegment = inputPath.getFileName();
        String nameStr = fileSegment != null ? fileSegment.toString() : "";
        int firstDotIdx = nameStr.indexOf('.');
        String downloadedName;
//            if (firstDotIdx > 0 && firstDotIdx < nameStr.length() - 1) {
//                downloadedName = nameStr.substring(0, firstDotIdx) + "_downloaded" + nameStr.substring(firstDotIdx);
//            } else {
//                downloadedName = nameStr + "_downloaded";
//            }

        if (firstDotIdx > 0) {
            downloadedName = nameStr.substring(0, firstDotIdx) + "_downloaded" + nameStr.substring(firstDotIdx);
        } else {
            downloadedName = nameStr + "_downloaded";
        }
        return downloadedName;
    }

    private void readFileSynchronously(String server, String filename) {
        try {
            FTPServiceClient ftpServiceClient;
            FTPServiceClient.FTPServiceClientBuilder builder = (new FTPServiceClient.FTPServiceClientBuilder())
                    .setServerAddress(server);
            ftpServiceClient = builder.build();

            logger.info("Initiating synchronous read call with the server");
            System.out.println("Initiating synchronous read call with the server");

            Iterator<ReadFileResult> responses = ftpServiceClient.readFileUsingBlockingStub(filename);

            // Iterate over the responses
            while (responses.hasNext()) {
                ReadFileResult response = responses.next();
                if (response.hasMessage()) {
                    logger.info("Received result from server: " + response.getMessage());
                    System.out.println("Received result from server: " + response.getMessage());
                } else {
                    ByteString content = response.getFileChuck().getContent();
                    logger.info("Received result from server: " + content.toString());
                    System.out.println("Received result from server: " + content.toStringUtf8());
                }
            }
            logger.info("Completed read call");
            System.out.println("Completed read call");

        } catch (IOException e) {
            logger.info("Encountered exception " + e);
        } catch (StatusRuntimeException e) {
            logger.error("Error from server: {}\n {}", e.toString(), e.getMessage());
        }
    }

    private void getFileAttrs(String server, String[] fileNames) {
        try {
            CountDownLatch countDownLatch = new CountDownLatch(1);
            FTPServiceClient ftpServiceClient;
            FTPServiceClient.FTPServiceClientBuilder builder = new FTPServiceClient.FTPServiceClientBuilder();
            ftpServiceClient = builder.
                    setServerAddress(server)
                    .build();

            StreamObserver<FileAttributesResult> responseStreamObserver = new StreamObserver<FileAttributesResult>() {
                @Override
                public void onNext(FileAttributesResult fileAttributesResult) {
                    if(fileAttributesResult.hasMessage()) {
                        logger.info("Received error message from server: {}", fileAttributesResult.getMessage());
                    } else {
                        logger.info("Received file attributes from server: {}", fileAttributesResult.getFileAttributes());
                    }

                    // Don't call this method here.
                    // since multiple request are sent for each filename
                    // calling countDown() on each response will release the latch prematurely after the first response.
                    // Ideally, CountDownLatch should be decremented once after all response are received, typically in onCompleted()

                    //countDownLatch.countDown();
                }

                @Override
                public void onError(Throwable t) {
                    logger.error("Error from server for getFileAttrs: {}\n {}", t.toString(), t.getMessage());
                    countDownLatch.countDown();
                }

                @Override
                public void onCompleted() {
                    logger.info("Completed get attributes call");
                    System.out.println("Completed get attributes call");
                    countDownLatch.countDown();
                }

            };

            ftpServiceClient.getFileAttributes(fileNames, responseStreamObserver);
            countDownLatch.await(5, TimeUnit.MINUTES);
        } catch (IOException | InterruptedException e) {
            logger.info("While processing getFileAttrs() \n Encountered exception {}", e.getMessage());
        }

    }

    public static void main(String[] args) {
        boolean failed = false;
        Options options = getCLIOptions();

        CommandLineParser parser = new DefaultParser();
        try {
            CommandLine cmdLine = parser.parse(options, args);

            int optionsCount = cmdLine.getOptions().length;
            String server;

            if(cmdLine.hasOption(SERVER)) {
                server = cmdLine.getOptionValue(SERVER);
            }else {
                throw new ParseException("Missing server address");
            }

            if(cmdLine.hasOption(ADD) && optionsCount == 3) {
                String fileToAdd = cmdLine.getOptionValue(ADD);
                String outputFileName = cmdLine.getOptionValue(OUT);
                (new SampleCLIClient()).addFile(server, fileToAdd, outputFileName);
            } else if (cmdLine.hasOption(DEL) && optionsCount == 2) {
                String fileToDelete = cmdLine.getOptionValue(DEL);
                (new SampleCLIClient()).deletedFile(server, fileToDelete);
            } else if (cmdLine.hasOption(READ) && optionsCount == 2) {
                String fileToRead = cmdLine.getOptionValue(READ);
                if(cmdLine.hasOption(BLOCKING)) {
                    (new SampleCLIClient()).readFileSynchronously(server, fileToRead);
                }
                (new SampleCLIClient()).readFile(server, fileToRead);
            } else if (cmdLine.hasOption(ATTR) && optionsCount == 2) {
                // Get all option values. This supports multiple values when passed as separate args
                // e.g., -attr file1.txt file2.py, or inside a single quoted argument, e.g., -attr "file1.txt file2.py"
                String[] rawValues = cmdLine.getOptionValues(ATTR);
                List<String> fileNameList = getFileNameList(rawValues);
                String[] fileNames = fileNameList.toArray(new String[0]);
                (new SampleCLIClient()).getFileAttrs(server, fileNames);
            } else {
                // provided command-line arguments are incorrect or insufficient
                // in this case we set the flag
                failed = true;
            }

        }catch (ParseException pe) {
            logger.info(pe.toString());
            failed = true;
        }

        if(failed) {
            printUsage();
        }
    }

    private static @NonNull List<String> getFileNameList(String[] rawValues) {
        List<String> fileNameList = new ArrayList<>();
        if (rawValues != null) {
            for (String val : rawValues) {
                // Check if a single argument string contains spaces
                if (val.contains(" ")) {
                    String[] parts = val.split(" ");
                    boolean allPartsHaveDot = true;
                    // Check if every split part contains a dot extension. If any part lacks a dot,
                    // we assume the value represents a single filename with spaces (e.g., "my file name.py")
                    for (String part : parts) {
                        if (!part.isEmpty() && part.indexOf('.') == -1) {
                            allPartsHaveDot = false;
                            break;
                        }
                    }
                    // If all parts look like separate files (each has a dot extension), split them
                    if (allPartsHaveDot) {
                        for (String part : parts) {
                            if (!part.isEmpty()) {
                                fileNameList.add(part);
                            }
                        }
                    } else {
                        // Otherwise, treat the entire string as a single filename containing spaces
                        fileNameList.add(val);
                    }
                } else {
                    fileNameList.add(val);
                }
            }
        }
        return fileNameList;
    }

    private static @NonNull Options getCLIOptions() {
        Options options = new Options();

        options.addOption(SERVER, true, "server address");
        options.addOption(ADD, true, "Add a file to the server's destination directory");
        options.addOption(DEL, true, "Delete a file in the server's destination directory");
        options.addOption(READ, true, "Read/download a file from the server's destination directory");
        options.addOption(ATTR, true, "get files' attributes from the server's destination directory");
        options.addOption(OUT, true, "destination filename when adding a file");
        options.addOption(BLOCKING, false, "read a file using a blocking stub");
        return options;
    }

    private static void printUsage() {
        // Print the formatted help message using apache commons CLI
        System.out.println("To add a file");
        System.out.println("java -cp ftp-service-cli-client-1.0.0.jar  com.jshubham.ftpservice.cliclient.SampleCLIClient -add <file-path-to-add>  -server <server-address> -out <destination-filename>");
        System.out.println("for example: java -cp ftp-service-cli-client-1.0.0.jar  com.jshubham.ftpservice.cliclient.SampleCLIClient -add /tmp/hiThere.py  -server localhost -out destFile.py");
        System.out.println("\n");
        System.out.println("To delete a file");
        System.out.println("java -cp ftp-service-cli-client-1.0.0.jar  com.jshubham.ftpservice.cliclient.SampleCLIClient -del <filename-to-delete>   -server <server-address>");
        System.out.println("for example: java -cp ftp-service-cli-client-1.0.0.jar  com.jshubham.ftpservice.cliclient.SampleCLIClient -del \"destFile.py\"   -server localhost");
        System.out.println("\n");
        System.out.println("To read/download a file");
        System.out.println("java -cp ftp-service-cli-client-1.0.0.jar  com.jshubham.ftpservice.cliclient.SampleCLIClient -read <filename-to-read>   -server <server-address>");
        System.out.println("for example: java -cp ftp-service-cli-client-1.0.0.jar  com.jshubham.ftpservice.cliclient.SampleCLIClient -read \"destFile.py\"   -server localhost");
        System.out.println("\n");
        System.out.println("To read a file using blocking stub");
        System.out.println("java -cp ftp-service-cli-client-1.0.0.jar  com.jshubham.ftpservice.cliclient.SampleCLIClient -read <filename-to-read>   -server <server-address> -blocking");
        System.out.println("for example: java -cp ftp-service-cli-client-1.0.0.jar  com.jshubham.ftpservice.cliclient.SampleCLIClient -read \"myFile.txt\"   -server localhost -blocking");
        System.out.println("\n");
        System.out.println("To get file attributes");
        System.out.println("java -cp ftp-service-cli-client-1.0.0.jar com.jshubham.ftpservice.cliclient.SampleCLIClient -attr \"<list-of-filenames>\"   -server <server-address>");
        System.out.println("for example: java -cp ftp-service-cli-client-1.0.0.jar  com.jshubham.ftpservice.cliclient.SampleCLIClient -read \"myFile.txt sample.cpp sample.py\"   -server localhost");
    }
}
