package client;

import com.google.common.annotations.VisibleForTesting;
import com.jshubham.ftpservice.autogenerated.FTPServiceGrpc;
import com.jshubham.ftpservice.autogenerated.MetaData;
import com.jshubham.ftpservice.autogenerated.Result;
import io.grpc.ManagedChannel;
import io.grpc.ManagedChannelBuilder;
import io.grpc.stub.StreamObserver;

import java.io.IOException;

import static utils.ClientConstants.*;

/**
 * This class exposes two methods add and delete that can be used by customers
 * to add or delete files in the server's destination directory.
 * Instantiating a single client and using it to execute multiple operations is
 * preferred and more than performant than instantiating a new client for every
 * operation. This client also encapsulates the logic to chunk larger files when
 * transferring them over to the server. By default the chunk size is set to 4KB.
 * Developers who choose to implement the gRCP client themselves will then need
 * to implement the chunking logic themselves.
 */
public class FTPServiceClient implements AutoCloseable{
    private FTPServiceGrpc.FTPServiceStub asyncStub;
    private ManagedChannel channel;
    private int chuckSizeInBytes;

    /**
     * Private constructor that takes in a builder object to instantiate a
     * client
     * @param builder
     * @throws IOException
     */
    private FTPServiceClient(FTPServiceClientBuilder builder) throws IOException {
        chuckSizeInBytes = builder.chunkSizeInBytes;
        String serviceName = builder.serverAddress;

        channel = ManagedChannelBuilder.forAddress(serviceName, builder.insecureModePort)
                                        .usePlaintext()
                                        .defaultLoadBalancingPolicy(ROUND_ROBIN)
                                        .overrideAuthority(builder.overrideAuthority)
                                        .build();

        asyncStub = FTPServiceGrpc.newStub(channel);
    }

    /**
     * Returns the gRPC async stub. This method is used only for unit tests.
     */
    @VisibleForTesting
    public FTPServiceGrpc.FTPServiceStub getAsyncStub() {
        return asyncStub;
    }

    /**
     *  Closes the managed channel
     * @throws Exception
     */
    @Override
    public void close() throws Exception {
        if(channel != null) {
            channel.shutdown();
        }
    }

    /**
     * This method deletes a given file in the server's destination directory if present.
     * In case the file doesn't exist the return status is set to FILE_NOT_PRESENT.
     * Directories are never deleted. Errors callbacks are invoked for either of these scenarios.
     * The return status is set to FAILED, when a file can't be deleted, e.g. due to permissions error.
     * A successful deletion results in the status set to SUCCESS.
     *
     * @param fileNameToDelete
     * @param resultStreamObserver
     */
    public void deleteFile(String fileNameToDelete, StreamObserver<Result> resultStreamObserver) {
        MetaData metaData = MetaData.newBuilder()
                .setName(fileNameToDelete)
                .build();
        asyncStub.deleteFile(metaData, resultStreamObserver);
    }

    /**
     * Use the client builder for instantiating FTPServiceClient objects. All
     * values are set to default when no parameters are overridden.
     */
    public static class FTPServiceClientBuilder {
        private int chunkSizeInBytes = DEFAULT_CHUNK_SIZE_IN_BYTES;
        private String serverAddress = LOCALHOST;
        private int insecureModePort = DEFAULT_INSECURE_PORT;
        private String overrideAuthority = OVERRIDE_AUTHORITY;

        public FTPServiceClientBuilder setChunkSizeInBytes(int chunkSizeInBytes) {
            this.chunkSizeInBytes = chunkSizeInBytes;
            return this;
        }

        public FTPServiceClientBuilder setServerAddress(String serverAddress) {
            this.serverAddress = serverAddress;
            return this;
        }

        public FTPServiceClientBuilder setInsecureModePort(int insecureModePort) {
            this.insecureModePort = insecureModePort;
            return this;
        }

        public FTPServiceClientBuilder setOverrideAuthority(String overrideAuthority) {
            this.overrideAuthority = overrideAuthority;
            return this;
        }

        public FTPServiceClient build() throws IOException {
            return new FTPServiceClient(this);
        }
    }
}
