package client;

import com.google.common.annotations.VisibleForTesting;
import com.google.protobuf.ByteString;
import com.jshubham.ftpservice.autogenerated.*;
import io.grpc.ManagedChannel;
import io.grpc.ManagedChannelBuilder;
import io.grpc.stub.StreamObserver;
import utils.ClientUtils;

import java.io.IOException;
import java.io.InputStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.Iterator;

import static java.lang.Thread.sleep;
import static utils.ClientConstants.*;

/**
 * This class exposes two methods add and delete that can be used by customers
 * to add or delete files in the server's destination directory.
 * Instantiating a single client and using it to execute multiple operations is
 * preferred and more than performant than instantiating a new client for every
 * operation. This client also encapsulates the logic to chunk larger files when
 * transferring them over to the server. By default the chunk size is set to 4KB.
 * Developers who choose to implement the gRCP client themselves will then need
 * to implement the chunking logic themselves.
 */
public class FTPServiceClient implements AutoCloseable{
    private FTPServiceGrpc.FTPServiceStub asyncStub;
    private FTPServiceGrpc.FTPServiceBlockingStub blockingStub;
    private ManagedChannel channel;
    private int chuckSizeInBytes;

    /**
     * Private constructor that takes in a builder object to instantiate a
     * client
     * @param builder
     * @throws IOException
     */
    private FTPServiceClient(FTPServiceClientBuilder builder) throws IOException {
        chuckSizeInBytes = builder.chunkSizeInBytes;
        String serviceName = builder.serverAddress;

        channel = ManagedChannelBuilder.forAddress(serviceName, builder.insecureModePort)
                                        .usePlaintext()
                                        .defaultLoadBalancingPolicy(ROUND_ROBIN)
                                        .overrideAuthority(builder.overrideAuthority)
                                        .build();

        asyncStub = FTPServiceGrpc.newStub(channel);
        blockingStub = FTPServiceGrpc.newBlockingStub(channel);
    }

    /**
     * Returns the gRPC async stub. This method is used only for unit tests.
     */
    @VisibleForTesting
    public FTPServiceGrpc.FTPServiceStub getAsyncStub() {
        return asyncStub;
    }

    /**
     *  Closes the managed channel
     * @throws Exception
     */
    @Override
    public void close() throws Exception {
        if(channel != null) {
            channel.shutdown();
        }
    }

    /**
     * This method gets the file attributes of the fileNames from server if they are present on it.
     * In case file doesn't exist a String message is returned
     * @param fileNames  Array of strings representing the names of the files for which
     *                  we want to retrieve attributes from the server.
     * @param resultStreamObserver It is a StreamObserver that allows the client to
     *                             receive asynchronous responses from the server.
     *                             It will handle the server’s response as FileAttributesResult messages
     */
    public void getFileAttributes(String[] fileNames, StreamObserver<FileAttributesResult> resultStreamObserver) {
        // Creating stream request observer to send stream of multiple requests
        StreamObserver<MetaData> requestObserver = asyncStub.getFileAttributes(resultStreamObserver);

        // sending requests
        for(String fileName : fileNames) {
            System.out.println("Sending request to get attributes of " + fileName);
            requestObserver.onNext(MetaData.newBuilder()
                            .setName(fileName)
                    .build());
            /* try {
                // sleeping after each request to make process of streaming more clear
                sleep(250);
            } catch (InterruptedException e) {
                System.out.println("Calling thread interrupted");
                throw new RuntimeException(e);
            }*/
        }

        // signaling server that the client is done with sending the data and the transmission is complete
        requestObserver.onCompleted();

    }

    /**
     * This method deletes a given file in the server's destination directory if present.
     * In case the file doesn't exist the return status is set to FILE_NOT_PRESENT.
     * Directories are never deleted. Errors callbacks are invoked for either of these scenarios.
     * The return status is set to FAILED, when a file can't be deleted, e.g. due to permissions error.
     * A successful deletion results in the status set to SUCCESS.
     *
     * @param fileNameToDelete
     * @param resultStreamObserver
     */
    public void deleteFile(String fileNameToDelete, StreamObserver<Result> resultStreamObserver) {
        MetaData metaData = MetaData.newBuilder()
                .setName(fileNameToDelete)
                .build();
        asyncStub.deleteFile(metaData, resultStreamObserver);
    }

    /**
     * This method transfers a given source file to the server's destination directory
     * with name destFileName. A large file is transferred in chunks and checksums are
     * matched to vet for transmission errors.
     * <p>
     * Note that the behavior of this method is
     * unknown if multiple threads or processes attempt to transfer a file in parallel
     * with the same destFileName.
     *
     * @param sourceFilePath
     * @param destFileName
     * @param resultStreamObserver
     */
    public void addFile(String sourceFilePath, String destFileName, StreamObserver<Result> resultStreamObserver) {
        // request observer
        StreamObserver<AddFileRequest> addFileRequestObserver = asyncStub.addFile(resultStreamObserver);
        Path path = Paths.get(sourceFilePath);

        // check if the input file exists
        if(!Files.exists(path)) throw new RuntimeException("File " + path.toString() + " does not exists");

        // build and send the metadata first
        AddFileRequest metadata = AddFileRequest.newBuilder()
                .setMetadata(MetaData.newBuilder()
                        .setName(destFileName).build())
                .build();
        addFileRequestObserver.onNext(metadata);

        // send the source file in chunks
        try (InputStream inputStream = Files.newInputStream(path)) {
            try {
                byte[] chunkContentBytes = new byte[chuckSizeInBytes];
                int chuckCount =1;
                int size; // to store the number of bytes read from the input stream in each iteration of the loop
                while ((size = inputStream.read(chunkContentBytes)) > 0) {
                    byte[] hash = ClientUtils.computeChecksum(chunkContentBytes, size);

                    AddFileRequest addFileChunkRequest = AddFileRequest.newBuilder()
                            .setFileChuck(FileChuck.newBuilder()
                                    .setContent(ByteString.copyFrom(chunkContentBytes, 0, size))
                                    .setChecksum(ByteString.copyFrom(hash, 0, hash.length))
                                    .build()
                            )
                            .build();
                    addFileRequestObserver.onNext(addFileChunkRequest);
                    System.out.println("No. of Chunks send till now: " + chuckCount);
                    chuckCount++;
                }
                // signaling all the chunks of file are send to server
                addFileRequestObserver.onCompleted();
            } catch (IOException ioException) {
                addFileRequestObserver.onError(new Exception(ioException.getMessage()));
            }
        } catch (IOException ioException) {
            addFileRequestObserver.onError(new Exception(ioException.getMessage()));
        }
    }

    /**
     * This a non-blocking or asynchronous version of readFile RPC method
     * This method transfers a given file with name fileNameToRead from the server's
     * destination directory, if present. A large file is transferred in chunks.
     * In case the file doesn't exist a String message is returned.
     *
     *
     * @param fileName - Filename on server to be downloaded/read
     * @param responseStreamObserver - Stream Observer to stream the chunks of the file back to client
     */

    public void readFile(String fileName, StreamObserver<ReadFileResult> responseStreamObserver) {
        MetaData metaData = MetaData.newBuilder()
                .setName(fileName)
                .build();
        asyncStub.readFile(metaData, responseStreamObserver);
    }

    /**
     * This is the blocking/synchronus version of readFile RPC method
     * It makes use of blocking stub which will block the calling thread
     * until the server has sent all the responses or an error occurs.
     * We iterate over the responses using the `Iterator` and process each response in sequence
     * @param filename
     * @return Iterator<ReadFileResult> Returns a Iterable collection of either the error message or the file chunks responses
     * from the server
     */
    public Iterator<ReadFileResult> readFileUsingBlockingStub(String filename) {
        MetaData metaData = MetaData.newBuilder().setName(filename).build();
        return blockingStub.readFile(metaData);
    }

    /**
     * Use the client builder for instantiating FTPServiceClient objects. All
     * values are set to default when no parameters are overridden.
     */
    public static class FTPServiceClientBuilder {
        private int chunkSizeInBytes = DEFAULT_CHUNK_SIZE_IN_BYTES;
        private String serverAddress = LOCALHOST;
        private int insecureModePort = DEFAULT_INSECURE_PORT;
        private String overrideAuthority = OVERRIDE_AUTHORITY;

        public FTPServiceClientBuilder setChunkSizeInBytes(int chunkSizeInBytes) {
            this.chunkSizeInBytes = chunkSizeInBytes;
            return this;
        }

        public FTPServiceClientBuilder setServerAddress(String serverAddress) {
            this.serverAddress = serverAddress;
            return this;
        }

        public FTPServiceClientBuilder setInsecureModePort(int insecureModePort) {
            this.insecureModePort = insecureModePort;
            return this;
        }

        public FTPServiceClientBuilder setOverrideAuthority(String overrideAuthority) {
            this.overrideAuthority = overrideAuthority;
            return this;
        }

        public FTPServiceClient build() throws IOException {
            return new FTPServiceClient(this);
        }
    }
}
