package client;

import com.google.common.annotations.VisibleForTesting;
import com.jshubham.ftpservice.autogenerated.FTPServiceGrpc;
import io.grpc.ManagedChannel;
import io.grpc.ManagedChannelBuilder;

import java.io.IOException;

import static utils.ClientConstants.*;

public class FTPServiceClient implements AutoCloseable{
    private FTPServiceGrpc.FTPServiceStub asyncStub;
    private ManagedChannel channel;
    private int chuckSizeInBytes;

    /**
     *
     * @param builder
     * @throws IOException
     */
    private FTPServiceClient(FTPServiceClientBuilder builder) throws IOException {
        chuckSizeInBytes = builder.chunkSizeInBytes;
        String serviceName = builder.serverAddress;

        channel = ManagedChannelBuilder.forAddress(serviceName, builder.insecureModePort)
                                        .usePlaintext()
                                        .defaultLoadBalancingPolicy(ROUND_ROBIN)
                                        .overrideAuthority(builder.overrideAuthority)
                                        .build();

        asyncStub = FTPServiceGrpc.newStub(channel);
    }

    /**
     * Returns the gRPC async stub. This method is used only for unit tests.
     */
    @VisibleForTesting
    public FTPServiceGrpc.FTPServiceStub getAsyncStub() {
        return asyncStub;
    }

    @Override
    public void close() throws Exception {
        if(channel != null) {
            channel.shutdown();
        }
    }

    public static class FTPServiceClientBuilder {
        private int chunkSizeInBytes = DEFAULT_CHUNK_SIZE_IN_BYTES;
        private String serverAddress = LOCALHOST;
        private int insecureModePort = DEFAULT_INSECURE_PORT;
        private String overrideAuthority = OVERRIDE_AUTHORITY;

        public FTPServiceClientBuilder setChunkSizeInBytes(int chunkSizeInBytes) {
            this.chunkSizeInBytes = chunkSizeInBytes;
            return this;
        }

        public FTPServiceClientBuilder setServerAddress(String serverAddress) {
            this.serverAddress = serverAddress;
            return this;
        }

        public FTPServiceClientBuilder setInsecureModePort(int insecureModePort) {
            this.insecureModePort = insecureModePort;
            return this;
        }

        public FTPServiceClientBuilder setOverrideAuthority(String overrideAuthority) {
            this.overrideAuthority = overrideAuthority;
            return this;
        }

        public FTPServiceClient build() throws IOException {
            return new FTPServiceClient(this);
        }
    }
}
