DESTINATION_DIRECTORY_ON_SERVER=/Users/shubhamjagtap/Developer/Practise Projects/grpc-ftp-project/uploaded_files/
TEMP_WRITE_PATH=/Users/shubhamjagtap/Developer/Practise Projects/grpc-ftp-project/uploaded_files/tmp
SERVER_CERT_PATH=certs/serverCert.pem
SERVER_KEY_PATH=certs/serverKey.pem
CA_CERT_PATH=certs/rootCACert.pem
RUN_IN_INSECURE_MODE=false