package com.jshubham.ftpservice.server;

import com.jshubham.ftpservice.autogenerated.AddFileRequest;
import com.jshubham.ftpservice.autogenerated.FTPServiceGrpc;
import com.jshubham.ftpservice.autogenerated.MetaData;
import com.jshubham.ftpservice.autogenerated.Result;
import com.jshubham.ftpservice.utils.ServerConfiguration;
import io.grpc.stub.StreamObserver;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

import java.io.File;
import java.nio.file.Path;

public class FTPService extends FTPServiceGrpc.FTPServiceImplBase    {
    private static final Logger logger = LogManager.getLogger(FTPService.class.getName());
    private final Path destinationDirPath;
    Path tmpPath;

    public FTPService(ServerConfiguration serverConfiguration) {
        destinationDirPath = new File(serverConfiguration.getDestinationDirectoryOnServer()).toPath();
        tmpPath = new File(serverConfiguration.getTempWritePath()).toPath();
    }

    @Override
    public void deleteFile(MetaData request, StreamObserver<Result> responseObserver) {
        super.deleteFile(request, responseObserver);
    }

    @Override
    public StreamObserver<AddFileRequest> addFile(StreamObserver<Result> responseObserver) {
        return super.addFile(responseObserver);
    }
}
