package com.jshubham.ftpservice.server;

import com.jshubham.ftpservice.autogenerated.*;
import com.jshubham.ftpservice.utils.ServerConfiguration;
import io.grpc.stub.StreamObserver;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

import java.io.File;
import java.nio.file.Path;

public class FTPService extends FTPServiceGrpc.FTPServiceImplBase    {
    private static final Logger logger = LogManager.getLogger(FTPService.class.getName());
    private final Path destinationDirPath;
    Path tmpPath;

    public FTPService(ServerConfiguration serverConfiguration) {
        destinationDirPath = new File(serverConfiguration.getDestinationDirectoryOnServer()).toPath();
        tmpPath = new File(serverConfiguration.getTempWritePath()).toPath();
    }

    @Override
    public void deleteFile(MetaData request, StreamObserver<Result> responseObserver) {
        String fileName = request.getName();
        File file = destinationDirPath.resolve(fileName).toFile();

        logger.info("Received the request to delete file {}" , fileName);

        if(file.isDirectory()) {
            responseObserver.onNext(Result.newBuilder()
                            .setStatus(Status.CANT_DELETE_DIR)
                    .build());
            logger.info("Trying to delete a directory {}" , fileName);
        } else if(file.exists()) {
            boolean success = false;
            try {
                success = file.delete();
            } catch (Exception e) {
                logger.info("Exception trying to delete file {} exception {}" , fileName, e);
            }
            responseObserver.onNext(Result.newBuilder()
                            .setStatus(success ? Status.SUCCESS : Status.FAILED)
                    .build());
            logger.info("Complete the request to delete file {} with status {}",
                    fileName, success ? Status.SUCCESS.toString() : Status.FAILED.toString());
        } else {
            responseObserver.onNext(Result.newBuilder()
                            .setStatus(Status.FILE_NOT_PRESENT)
                    .build());
            logger.info("Rejecting request to delete file {} as it doesn't exists.", fileName);
        }

        // marking completion of unary RPC request processing
        responseObserver.onCompleted();
    }

    @Override
    public StreamObserver<AddFileRequest> addFile(StreamObserver<Result> responseObserver) {
        return super.addFile(responseObserver);
    }
}
