package com.jshubham.ftpservice.server;

import com.google.protobuf.ByteString;
import com.jshubham.ftpservice.autogenerated.*;
import com.jshubham.ftpservice.utils.ServerConfiguration;
import com.jshubham.ftpservice.utils.ServerUtils;
import io.grpc.stub.StreamObserver;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.javatuples.Pair;

import java.io.File;
import java.io.IOException;
import java.io.OutputStream;
import java.nio.file.*;
import java.security.NoSuchAlgorithmException;

public class FTPService extends FTPServiceGrpc.FTPServiceImplBase    {
    private static final Logger logger = LogManager.getLogger(FTPService.class.getName());
    private final Path destinationDirPath;
    Path tmpPath;

    public FTPService(ServerConfiguration serverConfiguration) {
        destinationDirPath = new File(serverConfiguration.getDestinationDirectoryOnServer()).toPath();
        tmpPath = new File(serverConfiguration.getTempWritePath()).toPath();
    }

    @Override
    public void deleteFile(MetaData request, StreamObserver<Result> responseObserver) {
        String fileName = request.getName();
        File file = destinationDirPath.resolve(fileName).toFile();

        logger.info("Received the request to delete file {}" , fileName);

        if(file.isDirectory()) {
            responseObserver.onNext(Result.newBuilder()
                            .setStatus(Status.CANT_DELETE_DIR)
                    .build());
            logger.info("Trying to delete a directory {}" , fileName);
        } else if(file.exists()) {
            boolean success = false;
            try {
                success = file.delete();
            } catch (Exception e) {
                logger.info("Exception trying to delete file {} exception {}" , fileName, e);
            }
            responseObserver.onNext(Result.newBuilder()
                            .setStatus(success ? Status.SUCCESS : Status.FAILED)
                    .build());
            logger.info("Complete the request to delete file {} with status {}",
                    fileName, success ? Status.SUCCESS.toString() : Status.FAILED.toString());
        } else {
            responseObserver.onNext(Result.newBuilder()
                            .setStatus(Status.FILE_NOT_PRESENT)
                    .build());
            logger.info("Rejecting request to delete file {} as it doesn't exists.", fileName);
        }

        // marking completion of unary RPC request processing
        responseObserver.onCompleted();
    }

    /**
     * This method adds a file to the server's destination directory. Only
     * files can be added. The files are first written to /tmp
     * directory and then atomically moved to the destination directory
     *
     * @param responseObserver - Used to send Result message response back to the client
     * @return StreamObserver<AddFileRequest>
     */
    @Override
    public StreamObserver<AddFileRequest> addFile(StreamObserver<Result> responseObserver) {
        logger.info("Received request to add a file");

        return new StreamObserver<AddFileRequest>() {
            OutputStream writer;
            Status status = Status.IN_PROGRESS;
            String fileNameToWrite;
            @Override
            public void onNext(AddFileRequest request) {
                try {
                    // message has metadata, try to create the file in temp directory
                    if(request.hasMetadata()) {
                        fileNameToWrite = request.getMetadata().getName();

                        // Sanity check for filename
                        if(ServerUtils.isNullOrEmpty(fileNameToWrite)) {
                            status = Status.CANT_ADD_FILE_WITHOUT_NAME;
                            responseObserver.onNext(Result.newBuilder()
                                            .setStatus(status)
                                    .build());
                            responseObserver.onCompleted();
                            logger.info("Request to add a file with name {} as rejected", fileNameToWrite);
                        }else {
                            // The StandardOpenOption.CREATE option specifies that the file should be created if it
                            // doesn’t already exist.
                            // The StandardOpenOption.TRUNCATE_EXISTING option specifies that if the file already
                            // exists, its contents should be discarded and the file should be considered empty.
                            writer = Files.newOutputStream(tmpPath.resolve(fileNameToWrite), StandardOpenOption.CREATE,
                                    StandardOpenOption.TRUNCATE_EXISTING);
                            logger.info("Creating empty file  {} to write to.", fileNameToWrite);
                        }
                    }else {
                        // message has file chunk
                        if(writer == null) {
                            status = Status.METADATA_MISSING;
                            responseObserver.onNext(Result.newBuilder()
                                            .setStatus(status)
                                    .build());
                            responseObserver.onCompleted();
                            logger.info("Rejecting the request to add file for lack of metadata");
                        } else {
                            FileChuck fileChuck = request.getFileChuck();
                            ByteString receivedHash = fileChuck.getChecksum();
                            ByteString content = fileChuck.getContent();
                            if(!ServerUtils.doCheckSumMatch(content, receivedHash)) {
                                status = Status.CHECKSUM_MISMATCH;
                                responseObserver.onNext(Result.newBuilder().setStatus(status).build());
                                responseObserver.onCompleted();
                                logger.info("Rejecting request to add a file {} for checksum mismatch", fileNameToWrite);
                            } else {
                                logger.debug("Writing next chunk of data to file {}", fileNameToWrite);
                                writeFile(writer, content);
                            }
                        }
                    }
                } catch (IOException | NoSuchAlgorithmException e) {
                    status = Status.FAILED;
                    closeAndCleanUp(writer, fileNameToWrite, status);
                    responseObserver.onNext(Result.newBuilder().setStatus(status).build());
                    responseObserver.onCompleted();
                    logger.info("Aborting file transfer request due to exception {}", e.toString());
                }
            }

            @Override
            public void onError(Throwable t) {

            }

            @Override
            public void onCompleted() {
                Pair<Boolean, Status> isCloseAndMoveSuccess = closeAndMove(writer, fileNameToWrite);
                if (!isCloseAndMoveSuccess.getValue0()) {
                    status = isCloseAndMoveSuccess.getValue1();
                    logger.info("Rejecting the request to add file {} with status : {}", fileNameToWrite, status.toString());
                    responseObserver.onNext(Result.newBuilder().setStatus(status).build());
                    responseObserver.onCompleted();
                } else {
                    status = Status.IN_PROGRESS.equals(status) ? Status.SUCCESS : status;
                    responseObserver.onNext(Result.newBuilder().setStatus(status).build());
                    responseObserver.onCompleted();
                    logger.info("Request to add file {} completed with status {}", fileNameToWrite, status.toString() );
                }
            }
        };
    }

    // Auxiliary Methods of the FTPService

    private void writeFile(OutputStream writer, ByteString content) throws IOException {
        writer.write(content.toByteArray());
        writer.flush();
    }

    private boolean closeAndCleanUp(OutputStream writer, String filename, Status status) {
        boolean successFulClose = false;

        // attempt to close the writer
        try {
            if(writer != null){
                writer.close();
            }
            successFulClose = true;
        } catch (IOException exception) {
            logger.info("Unable to close writer for file {}",filename);
            status = Status.FAILED;
        }
        if(status.equals(Status.FAILED) && !ServerUtils.isNullOrEmpty(filename)) {
            File file = tmpPath.resolve(filename).toFile();
            if(file.exists()) {
                file.delete();
            }
        }
        return successFulClose;
    }

    private Pair<Boolean, Status> closeAndMove(OutputStream writer, String fileName) {
        boolean successfulClose = true;
        Status status;

        // attempt to close the writer
        try {
            if(writer != null) {
                writer.close();
            }else {
                // if writer is null then the file was never written in the
                // first place
                status = Status.FAILED;
                successfulClose = false;
                logger.info("File {} has its writer equal to null adn was never written to", fileName);
                return Pair.with(successfulClose, status);
            }
        } catch (IOException ioException) {
            status = Status.FAILED;
            successfulClose = false;
            logger.info("Failed to close the writer while writing file {} to destination directory with exception {}", fileName, ioException.toString());
            return Pair.with(successfulClose, status);
        }

        // attempt to atomically write to destination directory
        Path source = tmpPath.resolve(fileName);
        Path destination = destinationDirPath.resolve(fileName);
        try {
            //The StandardCopyOption.ATOMIC_MOVE ensures that the file move operation is performed atomically, meaning
            // that it either completes successfully or fails without leaving the file in an inconsistent state.
            Files.move(source, destination, StandardCopyOption.ATOMIC_MOVE);
            status = Status.SUCCESS;
        } catch (AtomicMoveNotSupportedException e) {
            successfulClose = false;
            status = Status.ATOMIC_FILE_MOVE_FAILED;
            logger.info("Atomic move of files isn't supported on the platform. {}", e.toString());
        } catch (IOException e) {
            successfulClose = false;
            status = Status.FAILED;
            logger.info("Failed to move file {} to destination directory with error : {}", fileName, e.toString());
        }
        return Pair.with(successfulClose, status);
    }
}
